spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transportion?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis:
  mapper-locations: classpath:mapper/*.xml



file:
  upload-dir: D:/Data/JavaTrain/SDJT/intelligentTransportion/intelligentTransportion/images/